/* Generated By:JavaCC: Do not edit this line. MatrixTreeConstants.java Version 5.0 */
package Matrix;

public interface MatrixTreeConstants
{
  public int JJTS = 0;
  public int JJTVOID = 1;
  public int JJTINPUT = 2;
  public int JJTOUTPUT = 3;
  public int JJTVALORES = 4;
  public int JJTINNERARRAY = 5;
  public int JJTTERM = 6;
  public int JJTMATHEXPRESSION = 7;
  public int JJTADD = 8;
  public int JJTSUB = 9;
  public int JJTMUL = 10;
  public int JJTTRA = 11;


  public String[] jjtNodeName = {
    "S",
    "void",
    "input",
    "output",
    "Valores",
    "InnerArray",
    "Term",
    "MathExpression",
    "Add",
    "Sub",
    "Mul",
    "Tra",
  };
}
/* JavaCC - OriginalChecksum=27c4a79329d8f3bd295f02e2f6ad19f0 (do not edit this line) */
