/* Generated By:JJTree&JavaCC: Do not edit this line. MatrixConstants.java */
package Matrix;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MatrixConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDMATRIX = 3;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;
  /** RegularExpression Id. */
  int TRANSPOSE = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int DOUBLE_POINT = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int BRACKET_LEFT = 15;
  /** RegularExpression Id. */
  int BRACKET_RIGHT = 16;
  /** RegularExpression Id. */
  int PARENTHESIS_LEFT = 17;
  /** RegularExpression Id. */
  int PARENTHESIS_RIGHT = 18;
  /** RegularExpression Id. */
  int INPUT = 19;
  /** RegularExpression Id. */
  int OUTPUT = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int LF = 23;
  /** RegularExpression Id. */
  int SYMBOL = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DSL = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*@MatrixDSL\"",
    "<token of kind 2>",
    "\"@MatrixDSL*/\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"\\\'\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"input\"",
    "\"output\"",
    "<DOUBLE>",
    "<DIGIT>",
    "\"\\n\"",
    "<SYMBOL>",
  };

}
