/* Generated By:JavaCC: Do not edit this line. MatrixTreeConstants.java Version 5.0 */
package Matrix;

public interface MatrixTreeConstants
{
  public int JJTS = 0;
  public int JJTVOID = 1;
  public int JJTINPUT = 2;
  public int JJTOUTPUT = 3;
  public int JJTINNERARRAY = 4;
  public int JJTTERM = 5;
  public int JJTADD = 6;
  public int JJTSUB = 7;
  public int JJTMUL = 8;
  public int JJTTRA = 9;


  public String[] jjtNodeName = {
    "S",
    "void",
    "input",
    "output",
    "InnerArray",
    "Term",
    "Add",
    "Sub",
    "Mul",
    "Tra",
  };
}
/* JavaCC - OriginalChecksum=ae71a9134ce19d9263a90361301b22c0 (do not edit this line) */
